<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Repository\CalendarRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Eccube/Repository/CalendarRepository.php';

return $this->privates['Eccube\\Repository\\CalendarRepository'] = new \Eccube\Repository\CalendarRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
