<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\AgeLimit\Repository\ConfigRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/app/Plugin/AgeLimit/Repository/ConfigRepository.php';

return $this->privates['Plugin\\AgeLimit\\Repository\\ConfigRepository'] = new \Plugin\AgeLimit\Repository\ConfigRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
