<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Extension\DoctrineOrmExtension' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Form/Extension/DoctrineOrmExtension.php';

return $this->privates['Eccube\\Form\\Extension\\DoctrineOrmExtension'] = new \Eccube\Form\Extension\DoctrineOrmExtension(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()));
