<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Command\InstallerCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Command/InstallerCommand.php';

$this->privates['Eccube\\Command\\InstallerCommand'] = $instance = new \Eccube\Command\InstallerCommand($this);

$instance->setName('eccube:install');

return $instance;
