<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Command\LoadDataFixturesEccubeCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Command/LoadDataFixturesEccubeCommand.php';

$this->privates['Eccube\\Command\\LoadDataFixturesEccubeCommand'] = $instance = new \Eccube\Command\LoadDataFixturesEccubeCommand($this);

$instance->setName('eccube:fixtures:load');

return $instance;
