<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.dao.customer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/Authentication/Provider/AuthenticationProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/Authentication/Provider/UserAuthenticationProvider.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/Authentication/Provider/DaoAuthenticationProvider.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/User/UserCheckerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Core/User/UserChecker.php';

return $this->privates['security.authentication.provider.dao.customer'] = new \Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider(($this->privates['Eccube\\Security\\Core\\User\\CustomerProvider'] ?? $this->load('getCustomerProviderService.php')), ($this->privates['security.user_checker'] ?? ($this->privates['security.user_checker'] = new \Symfony\Component\Security\Core\User\UserChecker())), 'customer', ($this->privates['security.encoder_factory.generic'] ?? $this->getSecurity_EncoderFactory_GenericService()), true);
