<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\AgeLimit\Form\Type\Admin\ConfigType' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/app/Plugin/AgeLimit/Form/Type/Admin/ConfigType.php';

return $this->privates['Plugin\\AgeLimit\\Form\\Type\\Admin\\ConfigType'] = new \Plugin\AgeLimit\Form\Type\Admin\ConfigType();
