<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.UPh4WFD.Eccube\Entity\Calendar' shared service.

$this->throw('Cannot autowire service ".service_locator.UPh4WFD": it references class "Eccube\\Entity\\Calendar" but no such service exists.');
