<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'exercise_html_purifier.default' shared service.

include_once \dirname(__DIR__, 4).'/vendor/ezyang/htmlpurifier/library/HTMLPurifier.php';
include_once \dirname(__DIR__, 4).'/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php';
include_once \dirname(__DIR__, 4).'/vendor/exercise/htmlpurifier-bundle/src/HTMLPurifierConfigFactory.php';

return $this->privates['exercise_html_purifier.default'] = new \HTMLPurifier(\Exercise\HTMLPurifierBundle\HTMLPurifierConfigFactory::create('default', ['Cache.SerializerPath' => ($this->targetDir.''.'/htmlpurifier')], NULL, [], [], [], []));
