<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'eccube.security.failure_handler' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Http/Authentication/AuthenticationFailureHandlerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security/Http/Authentication/DefaultAuthenticationFailureHandler.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Security/Http/Authentication/EccubeAuthenticationFailureHandler.php';

return $this->privates['eccube.security.failure_handler'] = new \Eccube\Security\Http\Authentication\EccubeAuthenticationFailureHandler(($this->services['http_kernel'] ?? $this->getHttpKernelService()), ($this->privates['security.http_utils'] ?? $this->load('getSecurity_HttpUtilsService.php')), [], ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
