<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'exercise_html_purifier.form.text_type_extension' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/exercise/htmlpurifier-bundle/src/Form/TypeExtension/HTMLPurifierTextTypeExtension.php';

return $this->privates['exercise_html_purifier.form.text_type_extension'] = new \Exercise\HTMLPurifierBundle\Form\TypeExtension\HTMLPurifierTextTypeExtension(($this->privates['exercise_html_purifier.purifiers_registry'] ?? $this->load('getExerciseHtmlPurifier_PurifiersRegistryService.php')));
