<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Command\GenerateProxyCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Command/ContainerAwareCommand.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Command/GenerateProxyCommand.php';

$this->privates['Eccube\\Command\\GenerateProxyCommand'] = $instance = new \Eccube\Command\GenerateProxyCommand(($this->privates['Eccube\\Service\\EntityProxyService'] ?? $this->load('getEntityProxyServiceService.php')));

$instance->setName('eccube:generate:proxies');

return $instance;
