<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Type\Admin\OrderStatusSettingType' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Form/Type/Admin/OrderStatusSettingType.php';

return $this->privates['Eccube\\Form\\Type\\Admin\\OrderStatusSettingType'] = new \Eccube\Form\Type\Admin\OrderStatusSettingType(($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))), ($this->privates['Eccube\\Repository\\Master\\OrderStatusColorRepository'] ?? $this->load('getOrderStatusColorRepositoryService.php')), ($this->privates['Eccube\\Repository\\Master\\CustomerOrderStatusRepository'] ?? $this->load('getCustomerOrderStatusRepositoryService.php')));
