<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Command\PluginGenerateCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Command/PluginGenerateCommand.php';

$this->privates['Eccube\\Command\\PluginGenerateCommand'] = $instance = new \Eccube\Command\PluginGenerateCommand($this);

$instance->setName('eccube:plugin:generate');

return $instance;
