<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Type\Admin\SearchCustomerType' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Form/Type/Admin/SearchCustomerType.php';

return $this->privates['Eccube\\Form\\Type\\Admin\\SearchCustomerType'] = new \Eccube\Form\Type\Admin\SearchCustomerType(($this->privates['Eccube\\Repository\\Master\\CustomerStatusRepository'] ?? $this->load('getCustomerStatusRepositoryService.php')), ($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))));
