<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Eccube\Controller\Admin\Setting\System\SystemController' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Eccube/Controller/Admin/Setting/System/SystemController.php';

return $this->services['Eccube\\Controller\\Admin\\Setting\\System\\SystemController'] = new \Eccube\Controller\Admin\Setting\System\SystemController(($this->services['Eccube\\Service\\SystemService'] ?? $this->getSystemServiceService()));
