<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UPh4WFD' shared service.

return $this->privates['.service_locator.UPh4WFD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Calendar' => ['privates', '.errored..service_locator.UPh4WFD.Eccube\\Entity\\Calendar', NULL, 'Cannot autowire service ".service_locator.UPh4WFD": it references class "Eccube\\Entity\\Calendar" but no such service exists.'],
], [
    'Calendar' => 'Eccube\\Entity\\Calendar',
]);
