<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Eccube\DependencyInjection\Facade\AnnotationReaderFacade' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Eccube/DependencyInjection/Facade/AnnotationReaderFacade.php';

return $this->services['Eccube\\DependencyInjection\\Facade\\AnnotationReaderFacade'] = new \Eccube\DependencyInjection\Facade\AnnotationReaderFacade(($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()));
