<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Extension\HTMLPurifierTextTypeExtension' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Form/Extension/HTMLPurifierTextTypeExtension.php';

return $this->privates['Eccube\\Form\\Extension\\HTMLPurifierTextTypeExtension'] = new \Eccube\Form\Extension\HTMLPurifierTextTypeExtension(($this->privates['Eccube\\Request\\Context'] ?? $this->getContextService()));
