<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Doctrine\EventSubscriber\InitSubscriber' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Doctrine/EventSubscriber/InitSubscriber.php';

return $this->privates['Eccube\\Doctrine\\EventSubscriber\\InitSubscriber'] = new \Eccube\Doctrine\EventSubscriber\InitSubscriber();
