<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Command\PluginEnableCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Command/PluginCommandTrait.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Command/PluginEnableCommand.php';

$this->privates['Eccube\\Command\\PluginEnableCommand'] = $instance = new \Eccube\Command\PluginEnableCommand();

$instance->setPluginService(($this->services['Eccube\\Service\\PluginService'] ?? $this->load('getPluginServiceService.php')));
$instance->setPluginRepository(($this->services['Eccube\\Repository\\PluginRepository'] ?? $this->getPluginRepositoryService()));
$instance->setName('eccube:plugin:enable');

return $instance;
