<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Eccube\Controller\Admin\Order\ShippingController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Controller/AbstractController.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Controller/Admin/Order/ShippingController.php';

$this->services['Eccube\\Controller\\Admin\\Order\\ShippingController'] = $instance = new \Eccube\Controller\Admin\Order\ShippingController(($this->privates['Eccube\\Service\\MailService'] ?? $this->load('getMailServiceService.php')), ($this->privates['Eccube\\Repository\\OrderItemRepository'] ?? $this->load('getOrderItemRepositoryService.php')), ($this->privates['Eccube\\Repository\\CategoryRepository'] ?? $this->load('getCategoryRepositoryService.php')), ($this->privates['Eccube\\Repository\\DeliveryRepository'] ?? $this->load('getDeliveryRepositoryService.php')), ($this->services['Eccube\\Service\\TaxRuleService'] ?? $this->load('getTaxRuleServiceService.php')), ($this->privates['Eccube\\Repository\\ShippingRepository'] ?? $this->load('getShippingRepositoryService.php')), ($this->services['serializer'] ?? $this->load('getSerializerService.php')), ($this->privates['Eccube\\Service\\OrderStateMachine'] ?? $this->load('getOrderStateMachineService.php')), ($this->privates['eccube.purchase.flow.order'] ?? $this->load('getEccube_Purchase_Flow_OrderService.php')));

$instance->setEccubeConfig(($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))));
$instance->setEntityManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));
$instance->setSession(($this->services['session'] ?? $this->getSessionService()));
$instance->setFormFactory(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')));
$instance->setEventDispatcher(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

return $instance;
