<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Type\Admin\SearchProductType' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/src/Eccube/Form/Type/Admin/SearchProductType.php';

return $this->privates['Eccube\\Form\\Type\\Admin\\SearchProductType'] = new \Eccube\Form\Type\Admin\SearchProductType(($this->privates['Eccube\\Repository\\Master\\ProductStatusRepository'] ?? $this->load('getProductStatusRepositoryService.php')), ($this->privates['Eccube\\Repository\\CategoryRepository'] ?? $this->load('getCategoryRepositoryService.php')), ($this->privates['Eccube\\Repository\\TagRepository'] ?? $this->load('getTagRepositoryService.php')));
