<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFPbc9Cb\EccubeEccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFPbc9Cb/EccubeEccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFPbc9Cb.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFPbc9Cb\EccubeEccube_KernelDevDebugContainer::class, EccubeEccube_KernelDevDebugContainer::class, false);
}

return new \ContainerFPbc9Cb\EccubeEccube_KernelDevDebugContainer([
    'container.build_hash' => 'FPbc9Cb',
    'container.build_id' => '1b37ab18',
    'container.build_time' => 1653044361,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFPbc9Cb');
